// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t7a0XnFsh6Y3pCBm_Tnxv6MrSzRwkGY',
    appId: '1:45487672779:web:f6551835c0b6d6ba4e7a4e',
    messagingSenderId: '45487672779',
    projectId: 'employee-52256',
    authDomain: 'employee-52256.firebaseapp.com',
    storageBucket: 'employee-52256.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmI6A0L3DDiSB1hDO3I7aU8FbYYBYqJTQ',
    appId: '1:45487672779:android:7bb2b5cbafa0123d4e7a4e',
    messagingSenderId: '45487672779',
    projectId: 'employee-52256',
    storageBucket: 'employee-52256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMWo2ynuESOHNZI1Kwj1bs6KmGU_OWUWw',
    appId: '1:45487672779:ios:839264feb91742724e7a4e',
    messagingSenderId: '45487672779',
    projectId: 'employee-52256',
    storageBucket: 'employee-52256.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMWo2ynuESOHNZI1Kwj1bs6KmGU_OWUWw',
    appId: '1:45487672779:ios:839264feb91742724e7a4e',
    messagingSenderId: '45487672779',
    projectId: 'employee-52256',
    storageBucket: 'employee-52256.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4t7a0XnFsh6Y3pCBm_Tnxv6MrSzRwkGY',
    appId: '1:45487672779:web:10f6f1459c4428244e7a4e',
    messagingSenderId: '45487672779',
    projectId: 'employee-52256',
    authDomain: 'employee-52256.firebaseapp.com',
    storageBucket: 'employee-52256.appspot.com',
  );
}
